#
# tmux.conf
#
# @author = himkt

# default config
set -g status-interval 2
set -g status-justify left
set -g default-terminal "screen-256color"
set -as terminal-overrides ",*:Tc"

# enable mouse mode
setw -g mode-keys vi
if-shell "command -v pbcopy" \
  "bind-key -T copy-mode-vi y     send -X copy-selection-and-cancel\\; run 'tmux save-buffer -|pbcopy'" \
  "bind-key -T copy-mode-vi y     send -X copy-selection-and-cancel"
if-shell "command -v pbcopy" \
  "bind-key -T copy-mode-vi Enter send -X copy-selection-and-cancel\\; run 'tmux save-buffer -|pbcopy'" \
  "bind-key -T copy-mode-vi Enter send -X copy-selection-and-cancel"

# color
set -g status-fg colour231
set -g status-bg colour234

# pane
set -g pane-border-style fg=colour240
set -g pane-active-border-style fg=colour31
set -g pane-border-status top
set -g pane-border-format "#{?pane_active,#[fg=colour31] [*] #T ,#[fg=colour240] #T }"

# window
window_accent="#{?client_prefix,colour160,colour31}"
window_style="#[fg=colour234,bg=$window_accent] #[fg=colour231,bg=$window_accent,bold]"
window_edge="#[fg=$window_accent,bg=colour234,nobold]"
set -g window-status-format "#[fg=colour244,bg=colour234]  #I #[fg=colour240] #[default]#W"
set -g window-status-current-format "$window_style #I #W $window_edge"

# take over current directory path
bind-key '"' split-window -c "#{pane_current_path}"
bind-key %   split-window -h -c "#{pane_current_path}"
bind-key c   new-window -c "#{pane_current_path}"

# status bar left
set -g status-left-length 40
set -qg status-left "#[fg=colour16,bg=colour231] #h "

# status bar right
set -g status-right ""

# tmux config
set -g escape-time 10
set -g history-limit 1000000
set -g display-panes-time 5000

bind ^h select-layout even-horizontal
bind ^v select-layout even-vertical

# NOTE Commands `search-xxx-incremental` is new feature, it counldn't use in some environments
#      For old tmux, please comment out following statement
bind-key -T copy-mode-vi / command-prompt -i -I "#{pane_search_string}" -p "(search down)" "send -X search-forward-incremental \"%%%\""
bind-key -T copy-mode-vi ? command-prompt -i -I "#{pane_search_string}" -p "(search up)" "send -X search-backward-incremental \"%%%\""
