# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-5e1d2de0-a651-4576-96f4-ceeb2e3e773b";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-5e1d2de0-a651-4576-96f4-ceeb2e3e773b".device = "/dev/disk/by-uuid/5e1d2de0-a651-4576-96f4-ceeb2e3e773b";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/8463-FB7A";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-8e3f8068-90b0-4614-a514-98ae63db54ab"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
